spring.application.name=AdvancedTodoAPI

# Enable the H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection Settings (In-Memory Database)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/master

#http://localhost:8080/h2-console